name: AsyncApiGo pipeline

on: 
  push:
  pull_request:
    types: [opened, reopened]

jobs:
#  golangci:
#    name: lint
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/setup-go@v3
#        with:
#          go-version: 1.18
#      - uses: actions/checkout@v3
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v3

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test ./...

    - name: Build_linux-x86-64
      run: GOOS=linux GOARCH=amd64 go build -o asyncapigo-linux-x64 ./main.go
    - name: Build_windows-x86-64
      run: GOOS=windows GOARCH=amd64 go build -o asyncapigo-windows-x64.exe ./main.go
    - name: Build_apple-silicon-x86-64
      run: GOOS=darwin GOARCH=arm64 go build -o asyncapigo-osx-arm-x64 ./main.go

    - uses: actions/upload-artifact@master
      with:
        name: asyncapigo
        path: ./asyncapigo-*